//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCover.UI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class OpenCoverUISettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static OpenCoverUISettings defaultInstance = ((OpenCoverUISettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OpenCoverUISettings())));
        
        public static OpenCoverUISettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NUnitPath {
            get {
                return ((string)(this["NUnitPath"]));
            }
            set {
                this["NUnitPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenCoverPath {
            get {
                return ((string)(this["OpenCoverPath"]));
            }
            set {
                this["OpenCoverPath"] = value;
            }
        }
    }
}
